### ISSUE TITLE
Implementing EntityInterface multiple times

### ISSUE THREAD

**Issue by filisko** [oscarotero/folk#3]
Hi,
Why you do this:
```php
abstract class SimpleCrud extends AbstractEntity implements EntityInterface
```
when you already have this?:
```php
abstract class AbstractEntity implements EntityInterface
```
Is there any particular reason to implement EntityInterface twice? 😃  (it happens the same with the other classes)

Cheers

**Comment by oscarotero** [comment]
Yes, you're right. It's redundant. I think this project needs an update but I don't have enough time 😃

**Comment by filisko** [comment]
That's what I thought :smile: Ok, If I have sometime I can improve that a little bit.

I think that the idea behind is so nice, I wanted to do something similar :smile: 

Thank you!

---

I'll better leave it open and submit a PR when I have some time.

**Comment by filisko** [comment]
#4 after nearly one year... haha
