### ISSUE TITLE
Fol\ContainerException:  / No PSR-17 factory detected to create a response 

### ISSUE THREAD

**Issue by graphis** [oscarotero/folk#5]
( ! ) Fol\ContainerException: Error retrieving middleware in /Users/mikka/Downloads/folk-3.7.3/vendor/oscarotero/fol/src/App.php on line 94

I have this issue with the demo stuff.  Am I missing something?

**Comment by oscarotero** [comment]
Probably you executed `composer update` instead `composer install`.

I've updated the packages and fixed the error (the zend-diactoros package was replaced by laminas-diactoros).
Now it should work fine.

**Comment by graphis** [comment]
True, I mistakenly executed composer update.
Thanks
